version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli-eslint
    versions:
    - "> 4.2.3"
  - dependency-name: ember-cli
    versions:
    - 3.23.0
    - 3.24.0
    - 3.25.0
  - dependency-name: ember-cli-typescript
    versions:
    - 4.0.0
  - dependency-name: ember-cli-htmlbars-inline-precompile
    versions:
    - 3.0.1
